# Generated by Django 4.0.4 on 2022-05-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_topic_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='name',
            field=models.CharField(default='匿名', max_length=100, verbose_name='名前'),
            preserve_default=False,
        ),
    ]
